class AddMissingSlugMigrations < ActiveRecord::Migration[5.2]
  def up
    return say("Skipping slug creation in test environment") if Rails.env.test?

    SLUGS.each do |s|
      execute "INSERT INTO slug_migrations (slug, created_at, updated_at, content_id) VALUES ('#{s}', now(), now(), '#{SecureRandom.uuid}')"
    end
  end

  SLUGS = [
    "/service-manual/communications/index.html",
    "/service-manual/web-ops/index.html",
    "/service-manual/developers/index.html",
    "/service-manual/agile/index.html",
    "/service-manual/digital-by-default/index.html",
    "/service-manual/feedback/index.html",
    "/service-manual/governance/index.html",
    "/service-manual/chief-technology-officers/index.html",
    "/service-manual/measurement/index.html",
    "/service-manual/domain-names/index.html",
    "/service-manual/the-team/recruitment/index.html",
    "/service-manual/the-team/learning-and-development/index.html",
    "/service-manual/the-team/index.html",
    "/service-manual/browse/index.html",
    "/service-manual/technology/index.html",
    "/service-manual/digital-by-default-26-points/index.html",
    "/service-manual/operations/index.html",
    "/service-manual/user-researchers/index.html",
    "/service-manual/user-centred-design/resources/elements/index.html",
    "/service-manual/user-centred-design/resources/patterns/index.html",
    "/service-manual/user-centred-design/user-research/index.html",
    "/service-manual/user-centred-design/index.html",
    "/service-manual/themes/index.html",
    "/service-manual/phases/index.html",
    "/service-manual/cards/index.html",
    "/service-manual/assisted-digital/index.html",
    "/service-manual/performance-analysts/index.html",
    "/service-manual/start/index.html",
    "/service-manual/designers/index.html",
    "/service-manual/making-software/index.html",
    "/service-manual/identity-assurance/index.html",
    "/service-manual/service-managers/index.html",
    "/service-manual/content-designers/index.html",
    "/service-manual/technical-architects/index.html",

    "/service-manual/communications/index",
    "/service-manual/web-ops/index",
    "/service-manual/developers/index",
    "/service-manual/agile/index",
    "/service-manual/digital-by-default/index",
    "/service-manual/feedback/index",
    "/service-manual/governance/index",
    "/service-manual/chief-technology-officers/index",
    "/service-manual/measurement/index",
    "/service-manual/domain-names/index",
    "/service-manual/the-team/recruitment/index",
    "/service-manual/the-team/learning-and-development/index",
    "/service-manual/the-team/index",
    "/service-manual/browse/index",
    "/service-manual/technology/index",
    "/service-manual/digital-by-default-26-points/index",
    "/service-manual/operations/index",
    "/service-manual/user-researchers/index",
    "/service-manual/user-centred-design/resources/elements/index",
    "/service-manual/user-centred-design/resources/patterns/index",
    "/service-manual/user-centred-design/user-research/index",
    "/service-manual/user-centred-design/index",
    "/service-manual/themes/index",
    "/service-manual/phases/index",
    "/service-manual/cards/index",
    "/service-manual/assisted-digital/index",
    "/service-manual/performance-analysts/index",
    "/service-manual/start/index",
    "/service-manual/designers/index",
    "/service-manual/making-software/index",
    "/service-manual/identity-assurance/index",
    "/service-manual/service-managers/index",
    "/service-manual/content-designers/index",
    "/service-manual/technical-architects/index",
  ].freeze
end
